Updated Demo & OnPlayerJoin
asadm/playroom-unity pull request #19
Opened 2023-09-08 12:01 UTC by momintlh

Added Jumping to the demo game
Updated OnPlayerJoin.

2023-09-09 12:25 UTC, SaadBazaz requested changes
Great job! Just some small changes. It's important to use the correct language, so that it's easy for future maintainers.

2023-09-09 12:25 UTC, SaadBazaz commented on Assets/PlayroomKit/PlayroomKit.cs
> +        private static extern void InsertCoinInternal(Action callback, string options, Action<string> onJoinCallBack ,Action<string> onQuitInternalCallback);
Small nits:
1. Rename `onJoinCallback` to `onPlayerJoinInternalCallback`
2. Fix space between comma and `onJoinCallback`

2023-09-09 12:25 UTC, SaadBazaz commented on Assets/PlayroomKit/PlayroomKit.cs
> +                    OnJoinCallbacks.Add(playerCallback);
Rename playerCallback to onPlayerJoinCallback

2023-09-09 12:25 UTC, SaadBazaz commented on Assets/PlayroomKit/PlayroomKit.cs
> +        private static List<Action<Player>> OnJoinCallbacks = new();
Rename onJoinCallbacks to onPlayerJoinCallbacks

2023-09-09 12:26 UTC, SaadBazaz commented
Add this demo game code to the docs: https://github.com/asadm/playroom-docs/blob/main/pages/usage/unity.mdx

2023-09-11 06:28 UTC, momintlh commented
Updated @SaadBazaz

2023-09-13 13:35 UTC, merged